# Wound Care Guide Configuration
# This file controls what appears in the guide and how it's formatted

# Document metadata
document:
  title: "Jovive Walnut Creek - wound care dressing guide"
  tagline: "Quick reference for wound care products available in clinic"
  author: "Medical Team"
  reference-url: "https://github.com/bobburgers7/wound-care-dressings"
  show-frequency: true
  date:
    year: 2025
    month: 9
    day: 8

# Main sections configuration - these appear in the primary guide
sections:
  ointments:
    title: "PRIMARY DRESSING OINTMENTS AND GELS"
    header-color: "#E6F3FF"
    note: "Each of these can be spread over a piece of oil emulsion gauze first, then applied to the wound, to ensure coverage of the wound bed."
    note_color: "#FFFACD"
    products:
      - "medihoney-gel"
      - "hydrogel" 
      - "iodosorb"
      - "betadine"
      - "mupirocin"
      - "gentamicin"
      - "zinc-oxide"
      - "nystatin-powder"
      - "lidocaine-ointment"

  peri-wound:
    title: "PERI-WOUND TREATMENTS"
    header-color: "#FFF0E6"
    products:
      - "triad-cream"
      - "calmoseptine-catalog"
      - "antifungal-cream"
      - "hydrocortisone-cream"
      - "triamcinolone-cream"
      - "aquaphor"
      - "gold-bond"
      - "amlactin"

  fillers:
    title: "PRIMARY DRESSINGS"
    header-color: "#E6FFE6"
    products:
      - "hydrofera-blue"
      - "adaptic"
      - "fibracol-collagen"
      - "xeroform"
      - "calcium-alginate-plain"
      - "calcium-alginate-ag"
      - "gelling-fiber-ag-rope"

  covers:
    title: "SECONDARY DRESSINGS"
    header-color: "#FFE6E6"
    products:
      - "telfa-pads"
      - "abd-pads"
      - "kerlix-wrap"
      - "foam-silicone"
      - "super-absorbent"
      - "spandagrip-e"
      - "spandagrip-f"
      - "spandagrip-g"
      - "hydrocellular-foam"
      - "hydrocolloid-thin"
      - "retention-tape-2in"
      - "cohesive-bandage-tan"
      - "conform-bandage"
      - "island-border-gauze"
      - "tubular-net-sz6"
      - "tubular-net-sz9"

  compression-wraps:
    title: "MULTI-LAYER COMPRESSION WRAPS"
    header-color: "#FFE6CC"
    note: "Used for venous insufficiency and edema control. Ensure arterial circulation is adequate before application."
    note_color: "#FFFACD"
    products:
      - "compression-k2-dual"
      - "compression-k2-lite"
      - "unna-boot"

# Catalog review section - toggle this on/off as needed
catalog-review:
  enabled: true  # Set to true to show catalog items in the guide
  title: "ADDITIONAL SUPPLIES AND TOOLS"
  header-color: "#F0F0F0"
  
  # Organize remaining catalog items by category
  categories:
    wound_care_supplies:
      title: "Additional Wound Care Supplies"
      products:
        - "saline-irrigation"
        - "wound-cleanser-spray"
        - "vashe-wound-wash"

    instruments_tools:
      title: "Instruments & Tools"
      products:
        - "silver-nitrate"
        - "biopsy-punch"
        - "dermal-curette-2mm"
        - "dermal-curette-4mm"
        - "surgical-blade-15"
        - "staple-remover"
        - "suture-removal-tray"
        - "wound-measuring-ruler"

    prep_cleaning:
      title: "Prep & Cleaning Supplies"
      products:
        - "adhesive-remover"
        - "alcohol-prep"
        - "povidone-prep"
        - "benzoin-tincture"
        - "skin-prep-wipes"
        - "sanicloth-wipes"

    basic_supplies:
      title: "Basic Supplies"
      products:
        - "gauze-sponge-2x2"
        - "gauze-sponge-4x4"
        - "cotton-tip-applicators"
        - "tongue-depressor"
        - "skin-closure-strips"
        - "paper-tape"

    specialty_items:
      title: "Specialty Items"
      products:
        - "nasal-packing-iodoform"
        - "nasal-packing-plain"
        - "ostomy-ring"
        - "saline-inhalation"

    general_supplies:
      title: "General Supplies"
      products: []

# Table formatting options
table:
  columns:
    image_width: "60pt"
    image_height: "40pt" 
    name_weight: "bold"
    description_size: "10pt"
    indication_style: "italic"
    indication_size: "9pt"

# Footer settings
footer:
  show_version: true
  version: "0.3.7"
  show_date: true
  font_size: "8pt"